# Generated by Django 5.0.9 on 2026-01-02 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0007_alter_customuser_options_alter_customuser_blink_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('work_extension', models.CharField(blank=True, help_text='z.B. 123 oder -123', max_length=10, verbose_name='Durchwahl')),
                ('private_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Telefonnummer muss im Format eingegeben werden: '+999999999'. Bis zu 15 Ziffern erlaubt.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Privat Telefon')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Notfallkontakt Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Telefonnummer muss im Format eingegeben werden: '+999999999'. Bis zu 15 Ziffern erlaubt.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Notfallkontakt Telefon')),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='z.B. Ehepartner, Eltern, Geschwister', max_length=100, verbose_name='Verhältnis zum Notfallkontakt')),
                ('office_location', models.CharField(blank=True, help_text='z.B. Hamburg HQ, Außendienst, Home Office', max_length=200, verbose_name='Bürostandort')),
                ('desk_number', models.CharField(blank=True, max_length=50, verbose_name='Schreibtisch/Raumnummer')),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'E-Mail'), ('phone', 'Telefon'), ('mobile', 'Mobil'), ('teams', 'Teams/Chat')], default='email', max_length=20, verbose_name='Bevorzugte Kontaktmethode')),
                ('teams_id', models.CharField(blank=True, max_length=200, verbose_name='Microsoft Teams ID')),
                ('slack_id', models.CharField(blank=True, max_length=200, verbose_name='Slack ID')),
                ('typical_work_hours', models.CharField(blank=True, help_text='z.B. Mo-Fr 8:00-16:30', max_length=200, verbose_name='Typische Arbeitszeiten')),
                ('timezone', models.CharField(blank=True, default='Europe/Berlin', max_length=50, verbose_name='Zeitzone')),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen (nur für HR/Admin sichtbar)', verbose_name='Notizen')),
                ('is_visible_in_directory', models.BooleanField(default=True, help_text='Im internen Mitarbeiterverzeichnis anzeigen', verbose_name='Im Verzeichnis sichtbar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kontaktprofil',
                'verbose_name_plural': 'Kontaktprofile',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['office_location', 'is_visible_in_directory'], name='contacts_co_office__c9a788_idx'), models.Index(fields=['is_visible_in_directory', 'user'], name='contacts_co_is_visi_f7c371_idx')],
            },
        ),
    ]
