# Generated by Django 5.2.4 on 2025-07-24 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sofortmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyNumber', models.CharField(default='15308598', max_length=50, verbose_name='Firmennummer')),
                ('insurance_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Sozialversicherungsnummer')),
                ('first_name', models.CharField(max_length=255, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nachname')),
                ('citizenship', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Staatsangehörigkeit')),
                ('group', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Personengruppenschlüssel')),
                ('start_date', models.DateField(verbose_name='Vertragsbeginn')),
                ('birth_land', models.CharField(blank=True, max_length=3, null=True, verbose_name='Geburtsland (Staatenkennzeichen)')),
                ('birth_gender', models.CharField(blank=True, choices=[('M', 'Männlich'), ('W', 'Weiblich'), ('D', 'Divers'), ('X', 'Unbestimmt')], max_length=1, null=True, verbose_name='Geschlecht (m/w/d/x)')),
                ('birth_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geburtsname')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geburtsort')),
                ('country_code', models.CharField(blank=True, default='D', max_length=2, null=True, verbose_name='Wohnland')),
                ('city_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wohnort')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postleitzahl')),
                ('street_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Straße')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('tan', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='TAN-Nummer')),
                ('url', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='PDF-Link')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Sofortmeldung',
                'verbose_name_plural': 'Sofortmeldungen',
            },
        ),
    ]
