# Generated by Django 5.0.9 on 2026-01-02 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofortmeldung', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sofortmeldung',
            options={'ordering': ['-createdAt'], 'verbose_name': 'Sofortmeldung', 'verbose_name_plural': 'Sofortmeldungen'},
        ),
        migrations.AddIndex(
            model_name='sofortmeldung',
            index=models.Index(fields=['status', '-createdAt'], name='sofortmeldu_status_d5c864_idx'),
        ),
        migrations.AddIndex(
            model_name='sofortmeldung',
            index=models.Index(fields=['insurance_number'], name='sofortmeldu_insuran_6769a5_idx'),
        ),
        migrations.AddIndex(
            model_name='sofortmeldung',
            index=models.Index(fields=['start_date'], name='sofortmeldu_start_d_2a8027_idx'),
        ),
        migrations.AddIndex(
            model_name='sofortmeldung',
            index=models.Index(fields=['createdBy', '-createdAt'], name='sofortmeldu_created_b928bb_idx'),
        ),
    ]
