# Generated by Django 5.0.9 on 2026-01-08 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofortmeldung', '0002_alter_sofortmeldung_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sofortmeldung',
            options={'ordering': ['-createdAt'], 'permissions': [('request_cancellation_sofortmeldung', 'Can request cancellation'), ('view_all_sofortmeldungen', 'Can view all sofortmeldungen (toggle)')], 'verbose_name': 'Sofortmeldung', 'verbose_name_plural': 'Sofortmeldungen'},
        ),
        migrations.AddField(
            model_name='sofortmeldung',
            name='assigned_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sofortmeldungen', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesener HR-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='sofortmeldung',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Stornierungsgrund'),
        ),
        migrations.AddField(
            model_name='sofortmeldung',
            name='cancellation_requested',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Stornierung angefragt'),
        ),
        migrations.AddField(
            model_name='sofortmeldung',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stornierung angefragt am'),
        ),
        migrations.AddField(
            model_name='sofortmeldung',
            name='cancellation_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_sofortmeldung_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='Stornierung angefragt von'),
        ),
        migrations.AddField(
            model_name='sofortmeldung',
            name='status_detail',
            field=models.CharField(choices=[('IN_BEARBEITUNG', 'In Bearbeitung'), ('GESENDET', 'Gesendet'), ('FEHLGESCHLAGEN', 'Fehlgeschlagen'), ('STORNIERUNG_ANGEFRAGT', 'Stornierung angefragt'), ('STORNIERT', 'Storniert')], db_index=True, default='IN_BEARBEITUNG', max_length=50, verbose_name='Status Detail'),
        ),
        migrations.AlterField(
            model_name='sofortmeldung',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sofortmeldungen', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='sofortmeldung',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status (Legacy)'),
        ),
        migrations.AddIndex(
            model_name='sofortmeldung',
            index=models.Index(fields=['status_detail', '-createdAt'], name='sofortmeldu_status__8a4603_idx'),
        ),
        migrations.AddIndex(
            model_name='sofortmeldung',
            index=models.Index(fields=['cancellation_requested', '-createdAt'], name='sofortmeldu_cancell_279e22_idx'),
        ),
    ]
