export const Countries = [
    { "value": "000", "title": "Deutschland" },
    { "value": "121", "title": "Albanien" },
    { "value": "122", "title": "Bosnien-Herzegowina" },
    { "value": "123", "title": "Andorra" },
    { "value": "124", "title": "Belgien" },
    { "value": "125", "title": "Bulgarien" },
    { "value": "126", "title": "Dänemark" },
    { "value": "127", "title": "Estland" },
    { "value": "128", "title": "Finnland" },
    { "value": "129", "title": "Frankreich" },
    { "value": "130", "title": "Kroatien" },
    { "value": "131", "title": "Slowenien" },
    { "value": "132", "title": "Serbien und Montenegro" },
    { "value": "133", "title": "Serbien (einschl. Kosovo)" },
    { "value": "134", "title": "Griechenland" },
    { "value": "135", "title": "Irland" },
    { "value": "136", "title": "Island" },
    { "value": "137", "title": "Italien" },
    { "value": "138", "title": "Jugoslawien" },
    { "value": "139", "title": "Lettland" },
    { "value": "140", "title": "Montenegro" },
    { "value": "141", "title": "Liechtenstein" },
    { "value": "142", "title": "Litauen" },
    { "value": "143", "title": "Luxemburg" },
    { "value": "144", "title": "Nordmazedonien" },
    { "value": "145", "title": "Malta" },
    { "value": "146", "title": "Moldau" },
    { "value": "147", "title": "Monaco" },
    { "value": "148", "title": "Niederlande" },
    { "value": "149", "title": "Norwegen" },
    { "value": "150", "title": "Kosovo" },
    { "value": "151", "title": "Österreich" },
    { "value": "152", "title": "Polen" },
    { "value": "153", "title": "Portugal" },
    { "value": "154", "title": "Rumänien" },
    { "value": "155", "title": "Slowakei" },
    { "value": "156", "title": "San Marino" },
    { "value": "157", "title": "Schweden" },
    { "value": "158", "title": "Schweiz" },
    { "value": "160", "title": "Russische Förderation" },
    { "value": "161", "title": "Spanien, Melilla, Ceuta" },
    { "value": "163", "title": "Türkei" },
    { "value": "164", "title": "Tschechien" },
    { "value": "165", "title": "Ungarn" },
    { "value": "166", "title": "Ukraine" },
    { "value": "167", "title": "Vatikanstadt" },
    { "value": "168", "title": "Großbritannien und Nordirland" },
    { "value": "169", "title": "Weißrussland" },
    { "value": "170", "title": "Serbien" },
    { "value": "181", "title": "Zypern" },
    { "value": "185", "title": "brit.abh.Gebiete ohne EU BOTC" },
    { "value": "195", "title": "brit.abh.Gebiete in Europa" },
    { "value": "199", "title": "übriges Europa" },
    { "value": "221", "title": "Algerien" },
    { "value": "223", "title": "Angola" },
    { "value": "224", "title": "Eritrea" },
    { "value": "225", "title": "Äthiopien" },
    { "value": "226", "title": "Lesotho" },
    { "value": "227", "title": "Botsuana" },
    { "value": "229", "title": "Benin" },
    { "value": "230", "title": "Dschibuti" },
    { "value": "231", "title": "Cote d' Ivoire" },
    { "value": "232", "title": "Nigeria" },
    { "value": "233", "title": "Simbabwe" },
    { "value": "236", "title": "Gabun" },
    { "value": "237", "title": "Gambia" },
    { "value": "238", "title": "Ghana" },
    { "value": "239", "title": "Mauretanien" },
    { "value": "242", "title": "Cabo Verde, Kap Verde" },
    { "value": "243", "title": "Kenia" },
    { "value": "244", "title": "Komoren" },
    { "value": "245", "title": "Kongo" },
    { "value": "246", "title": "Kongo, Dem. Republik" },
    { "value": "247", "title": "Liberia" },
    { "value": "248", "title": "Libyen" },
    { "value": "249", "title": "Madagaskar" },
    { "value": "251", "title": "Mali" },
    { "value": "252", "title": "Marokko" },
    { "value": "253", "title": "Mauritius" },
    { "value": "254", "title": "Mosambik" },
    { "value": "255", "title": "Niger" },
    { "value": "256", "title": "Malawi" },
    { "value": "257", "title": "Sambia" },
    { "value": "258", "title": "Burkina Faso" },
    { "value": "259", "title": "Guinea-Bissau" },
    { "value": "261", "title": "Guinea" },
    { "value": "262", "title": "Kamerun" },
    { "value": "263", "title": "Südafrika" },
    { "value": "265", "title": "Ruanda" },
    { "value": "267", "title": "Namibia" },
    { "value": "268", "title": "Sao Tome und Principe" },
    { "value": "269", "title": "Senegal" },
    { "value": "271", "title": "Seychellen" },
    { "value": "272", "title": "Sierra Leone" },
    { "value": "273", "title": "Somalia" },
    { "value": "274", "title": "Äquatorialguinea" },
    { "value": "276", "title": "Sudan" },
    { "value": "277", "title": "Sudan" },
    { "value": "278", "title": "Südsudan" },
    { "value": "281", "title": "Eswatini" },
    { "value": "282", "title": "Tansania" },
    { "value": "283", "title": "Togo" },
    { "value": "284", "title": "Tschad" },
    { "value": "285", "title": "Tunesien" },
    { "value": "286", "title": "Uganda" },
    { "value": "287", "title": "Ägypten" },
    { "value": "289", "title": "Zentralafrikanische Republik" },
    { "value": "291", "title": "Burundi" },
    { "value": "295", "title": "brit.abh. Gebiete Afrika" },
    { "value": "299", "title": "übriges Afrika" },
    { "value": "320", "title": "Antigua und Barbuda" },
    { "value": "322", "title": "Barbados" },
    { "value": "323", "title": "Argentinien" },
    { "value": "324", "title": "Bahamas" },
    { "value": "326", "title": "Bolivien" },
    { "value": "327", "title": "Brasilien" },
    { "value": "328", "title": "Guyana" },
    { "value": "330", "title": "Belize" },
    { "value": "332", "title": "Chile" },
    { "value": "333", "title": "Dominica" },
    { "value": "334", "title": "Costa-Rica" },
    { "value": "335", "title": "Dominikanische Republik" },
    { "value": "336", "title": "Ecuador" },
    { "value": "337", "title": "El Salvador" },
    { "value": "340", "title": "Grenada" },
    { "value": "345", "title": "Guatemala" },
    { "value": "346", "title": "Haiti" },
    { "value": "347", "title": "Honduras" },
    { "value": "348", "title": "Kanada" },
    { "value": "349", "title": "Kolumbien" },
    { "value": "351", "title": "Kuba" },
    { "value": "353", "title": "Mexiko" },
    { "value": "354", "title": "Nicaragua" },
    { "value": "355", "title": "Jamaika" },
    { "value": "357", "title": "Panama" },
    { "value": "359", "title": "Paraguay" },
    { "value": "361", "title": "Peru" },
    { "value": "364", "title": "Suriname" },
    { "value": "365", "title": "Uruguay" },
    { "value": "366", "title": "St. Lucia" },
    { "value": "367", "title": "Venezuela" },
    { "value": "368", "title": "Vereinigte Staaten" },
    { "value": "369", "title": "St. Vincent und die Grenadien" },
    { "value": "370", "title": "St. Kitts und Nevis" },
    { "value": "371", "title": "Trinidad und Tobago" },
    { "value": "395", "title": "brit. abhängige Geb. ohne EU" },
    { "value": "399", "title": "übriges Amerika" },
    { "value": "411", "title": "Hongkong" },
    { "value": "412", "title": "Macau" },
    { "value": "421", "title": "Jemen" },
    { "value": "422", "title": "Armenien" },
    { "value": "423", "title": "Afghanistan" },
    { "value": "424", "title": "Bahrain" },
    { "value": "425", "title": "Aserbaidschan" },
    { "value": "426", "title": "Bhutan" },
    { "value": "427", "title": "Myanmar" },
    { "value": "429", "title": "Brunei Darussalam" },
    { "value": "430", "title": "Georgien" },
    { "value": "431", "title": "Sri Lanka" },
    { "value": "432", "title": "Vietnam" },
    { "value": "434", "title": "Korea Dem. Volksrepublik" },
    { "value": "436", "title": "Indien" },
    { "value": "437", "title": "Indonesien, einschl. Irian Jay" },
    { "value": "438", "title": "Irak" },
    { "value": "439", "title": "Iran, Islamische Republik" },
    { "value": "441", "title": "Israel" },
    { "value": "442", "title": "Japan" },
    { "value": "444", "title": "Kasachstan" },
    { "value": "445", "title": "Jordanien" },
    { "value": "446", "title": "Kambodscha" },
    { "value": "447", "title": "Katar" },
    { "value": "448", "title": "Kuwait" },
    { "value": "449", "title": "Laos" },
    { "value": "450", "title": "Kirgisistan" },
    { "value": "451", "title": "Libanon" },
    { "value": "454", "title": "Malediven" },
    { "value": "456", "title": "Oman" },
    { "value": "457", "title": "Mongolei" },
    { "value": "458", "title": "Nepal" },
    { "value": "459", "title": "Palästinensische Gebiete" },
    { "value": "460", "title": "Bangladesch" },
    { "value": "461", "title": "Pakistan" },
    { "value": "462", "title": "Philippinen" },
    { "value": "465", "title": "Taiwan" },
    { "value": "467", "title": "Korea, Republik" },
    { "value": "469", "title": "Vereinigte Arabische Emirate" },
    { "value": "470", "title": "Tadschikistan" },
    { "value": "471", "title": "Turkmenistan" },
    { "value": "472", "title": "Saudi-Arabien" },
    { "value": "474", "title": "Singapur" },
    { "value": "475", "title": "Syrien" },
    { "value": "476", "title": "Thailand" },
    { "value": "477", "title": "Usbekistan" },
    { "value": "479", "title": "China, Tibet" },
    { "value": "482", "title": "Malaysia" },
    { "value": "483", "title": "Timor-Leste" },
    { "value": "495", "title": "brit.abh.Gebiete in Asien" },
    { "value": "499", "title": "übriges Asien" },
    { "value": "523", "title": "Australien, einschl. Kokos-, W" },
    { "value": "524", "title": "Salomonen" },
    { "value": "525", "title": "Nördliche Marianen" },
    { "value": "526", "title": "Fidschi" },
    { "value": "527", "title": "Cookinseln" },
    { "value": "530", "title": "Kiribati" },
    { "value": "531", "title": "Nauru" },
    { "value": "532", "title": "Vanuatu" },
    { "value": "533", "title": "Niue" },
    { "value": "536", "title": "Neuseeland" },
    { "value": "537", "title": "Palau" },
    { "value": "538", "title": "Papua-Neuguinea" },
    { "value": "540", "title": "Tuvalu" },
    { "value": "541", "title": "Tonga" },
    { "value": "543", "title": "Samoa" },
    { "value": "544", "title": "Marshallinseln" },
    { "value": "545", "title": "Mikronesien" },
    { "value": "595", "title": "brit. abh. Australien/Ozeanien" },
    { "value": "599", "title": "übriges Ozeanien" },
    { "value": "996", "title": "unbekanntes Ausland" },
    { "value": "997", "title": "staatenlos" },
    { "value": "998", "title": "ungeklärt" },
    { "value": "999", "title": "ohne Angabe" }
]
