# Generated by Django 5.1.7 on 2025-09-02 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_absence_representative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vacation', 'Urlaub'), ('sick_leave', 'Krankmeldung'), ('personal_leave', 'Persönlicher Grund'), ('training', 'Fortbildung'), ('business_trip', 'Geschäftsreise'), ('maternity_leave', 'Mutterschutz'), ('parental_leave', 'Elternzeit'), ('unpaid_leave', 'Unbezahlter Urlaub')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_certificate', models.BooleanField(default=False)),
                ('advance_notice_days', models.PositiveIntegerField(default=0)),
                ('max_consecutive_days', models.PositiveIntegerField(blank=True, null=True)),
                ('color_code', models.CharField(default='#007bff', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abwesenheitstyp',
                'verbose_name_plural': 'Abwesenheitstypen',
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-start_date'], 'verbose_name': 'Abwesenheit', 'verbose_name_plural': 'Abwesenheiten'},
        ),
        migrations.AddField(
            model_name='absence',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='absence_documents/'),
        ),
        migrations.AddField(
            model_name='absence',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='absence_certificates/'),
        ),
        migrations.AddField(
            model_name='absence',
            name='hr_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='hr_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absence',
            name='hr_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='representative_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absence',
            name='representative_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('hr_notified', 'HR Benachrichtigt'), ('cancelled', 'Storniert')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='absence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='approved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='AbsenceConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('team_overlap', 'Team-Überschneidung'), ('representative_conflict', 'Vertretungskonflikt'), ('department_shortage', 'Abteilungs-Engpass'), ('critical_period', 'Kritischer Zeitraum')], max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='absences.absence')),
                ('conflicting_absence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicted_by', to='absences.absence')),
            ],
            options={
                'verbose_name': 'Abwesenheitskonflikt',
                'verbose_name_plural': 'Abwesenheitskonflikte',
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='absences.absencetype'),
        ),
    ]
