# Generated by Django 5.1.7 on 2025-09-02 07:52

from django.db import migrations


def create_default_absence_types(apps, schema_editor):
    """Erstellt Standard-Abwesenheitstypen"""
    AbsenceType = apps.get_model('absences', 'AbsenceType')
    Absence = apps.get_model('absences', 'Absence')
    
    # Standard-Abwesenheitstypen erstellen
    absence_types = [
        {
            'name': 'vacation',
            'display_name': 'Urlaub',
            'description': 'Regulärer Jahresurlaub',
            'requires_approval': True,
            'requires_certificate': False,
            'advance_notice_days': 14,
            'max_consecutive_days': 21,
            'color_code': '#28a745',
            'is_active': True,
        },
        {
            'name': 'sick_leave',
            'display_name': 'Krankmeldung',
            'description': 'Krankheitsbedingte Abwesenheit',
            'requires_approval': False,
            'requires_certificate': True,
            'advance_notice_days': 0,
            'max_consecutive_days': None,
            'color_code': '#dc3545',
            'is_active': True,
        },
        {
            'name': 'personal_leave',
            'display_name': 'Persönlicher Grund',
            'description': 'Abwesenheit aus persönlichen Gründen',
            'requires_approval': True,
            'requires_certificate': False,
            'advance_notice_days': 7,
            'max_consecutive_days': 5,
            'color_code': '#ffc107',
            'is_active': True,
        },
        {
            'name': 'training',
            'display_name': 'Fortbildung',
            'description': 'Weiterbildung und Schulungen',
            'requires_approval': True,
            'requires_certificate': False,
            'advance_notice_days': 21,
            'max_consecutive_days': None,
            'color_code': '#17a2b8',
            'is_active': True,
        },
        {
            'name': 'business_trip',
            'display_name': 'Geschäftsreise',
            'description': 'Dienstreisen und Außentermine',
            'requires_approval': True,
            'requires_certificate': False,
            'advance_notice_days': 7,
            'max_consecutive_days': None,
            'color_code': '#6f42c1',
            'is_active': True,
        },
    ]
    
    # AbsenceTypes erstellen
    created_types = {}
    for type_data in absence_types:
        absence_type, created = AbsenceType.objects.get_or_create(
            name=type_data['name'],
            defaults=type_data
        )
        created_types[type_data['name']] = absence_type
    
    # Bestehende Absences mit default absence_type (vacation) verknüpfen
    vacation_type = created_types.get('vacation')
    if vacation_type:
        Absence.objects.filter(absence_type__isnull=True).update(absence_type=vacation_type)


def reverse_create_default_absence_types(apps, schema_editor):
    """Entfernt Standard-Abwesenheitstypen"""
    AbsenceType = apps.get_model('absences', 'AbsenceType')
    AbsenceType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_absencetype_alter_absence_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_default_absence_types,
            reverse_create_default_absence_types,
        ),
    ]
