# Generated by Django 5.1.7 on 2025-09-02 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0006_alter_absence_absence_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='hr_processed',
            field=models.BooleanField(default=False, help_text='Von HR als bearbeitet markiert'),
        ),
        migrations.AddField(
            model_name='absence',
            name='hr_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='hr_processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_processed_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='is_revision',
            field=models.BooleanField(default=False, help_text='Kennzeichnet eine überarbeitete Version'),
        ),
        migrations.AddField(
            model_name='absence',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='absences.absence'),
        ),
        migrations.AddField(
            model_name='absence',
            name='revision_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='absences.absencetype'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('hr_processed', 'HR Bearbeitet'), ('cancelled', 'Storniert'), ('revision_requested', 'Überarbeitung angefordert')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AbsenceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('user_comment', 'Benutzer Kommentar'), ('supervisor_feedback', 'Vorgesetzten Feedback'), ('hr_note', 'HR Notiz'), ('revision_request', 'Überarbeitungsanfrage'), ('approval_note', 'Genehmigungsnotiz'), ('rejection_note', 'Ablehnungsnotiz')], default='user_comment', max_length=20)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Nur für HR/Vorgesetzte sichtbar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='absences.absence')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abwesenheits-Kommentar',
                'verbose_name_plural': 'Abwesenheits-Kommentare',
                'ordering': ['-created_at'],
            },
        ),
    ]
