# Generated by Django 5.0.9 on 2025-11-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0008_add_manual_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencetype',
            name='name',
            field=models.CharField(choices=[('vacation', 'Urlaub'), ('sick_leave', 'Krankmeldung'), ('personal_leave', 'Persönlicher Grund'), ('training', 'Fortbildung'), ('business_trip', 'Geschäftsreise'), ('maternity_leave', 'Mutterschutz'), ('parental_leave', 'Elternzeit'), ('unpaid_leave', 'Unbezahlter Urlaub'), ('public_holiday', 'Feiertag')], max_length=50, unique=True),
        ),
    ]
