# Generated by Django 5.0.9 on 2025-11-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0009_alter_absencetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencetype',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex-Farbe für UI', max_length=7),
        ),
        migrations.AddField(
            model_name='absencetype',
            name='deduct_from_vacation',
            field=models.BooleanField(default=False, help_text='Von Urlaubskonto abziehen'),
        ),
        migrations.AddField(
            model_name='absencetype',
            name='icon',
            field=models.CharField(default='calendar-outline', help_text='Ionic Icon Name', max_length=50),
        ),
    ]
