# Generated by Django 5.0.9 on 2025-12-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0010_absencetype_color_absencetype_deduct_from_vacation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencetype',
            name='show_in_user_list',
            field=models.BooleanField(default=True, help_text='In der Abwesenheitsliste des Nutzers anzeigen'),
        ),
    ]
