# Generated by Django 5.0.9 on 2025-12-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0011_absencetype_show_in_user_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencetype',
            name='show_in_user_list',
        ),
    ]
