# Generated by Django 5.0.9 on 2025-12-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0012_remove_absencetype_show_in_user_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencetype',
            name='color_code',
        ),
    ]
