# Generated by Django 5.0.9 on 2026-01-02 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0013_remove_absencetype_color_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['user', 'status', 'start_date'], name='absences_ab_user_id_961591_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['absence_type', 'status'], name='absences_ab_absence_997ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['start_date', 'end_date'], name='absences_ab_start_d_9861ce_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['status', '-created_at'], name='absences_ab_status_077d54_idx'),
        ),
        migrations.AddIndex(
            model_name='absencetype',
            index=models.Index(fields=['name', 'is_active'], name='absences_ab_name_385588_idx'),
        ),
    ]
