# Generated by Django 5.0.9 on 2026-01-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0014_absence_absences_ab_user_id_961591_idx_and_more'),
        ('auth_user', '0025_chatmessage_metadata_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='change_history',
            field=models.JSONField(blank=True, default=list, help_text='Liste von Änderungen: [{timestamp, user, field, old_value, new_value, reason}]'),
        ),
        migrations.AddField(
            model_name='absence',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Chat-Konversation für Antrag und Genehmigung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_requests', to='auth_user.chatconversation'),
        ),
    ]
