# Generated by Django 5.0.9 on 2026-01-08 12:19

from django.db import migrations


def fill_representative(apps, schema_editor):
    """
    Füllt das representative-Feld für alle Absences ohne Vertretung.
    
    Strategie:
    1. Supervisor aus UserProfile.direct_supervisor
    2. Fallback: Erster aktiver Superuser
    """
    Absence = apps.get_model('absences', 'Absence')
    User = apps.get_model('auth_user', 'CustomUser')
    UserProfile = apps.get_model('auth_user', 'UserProfile')
    
    # Absences ohne representative
    absences_without_rep = Absence.objects.filter(representative__isnull=True)
    
    if not absences_without_rep.exists():
        return  # Nichts zu tun
    
    # Fallback: Erster Superuser
    fallback_user = User.objects.filter(is_superuser=True, is_active=True).first()
    
    if not fallback_user:
        # Wenn kein Superuser existiert, ersten Staff-User nehmen
        fallback_user = User.objects.filter(is_staff=True, is_active=True).first()
    
    if not fallback_user:
        # Wenn weder Superuser noch Staff existiert, IRGENDEIN User
        fallback_user = User.objects.filter(is_active=True).first()
    
    updated = 0
    for absence in absences_without_rep:
        representative = None
        
        # Versuche Supervisor aus UserProfile
        try:
            profile = UserProfile.objects.get(user=absence.user)
            if profile.direct_supervisor and profile.direct_supervisor.is_active:
                representative = profile.direct_supervisor
        except UserProfile.DoesNotExist:
            pass
        
        # Fallback
        if not representative:
            representative = fallback_user
        
        if representative:
            absence.representative = representative
            absence.save(update_fields=['representative'])
            updated += 1
    
    print(f"✅ {updated} Absences mit Vertretung befüllt (Fallback: {fallback_user})")


def reverse_fill(apps, schema_editor):
    """Reverse: Setze representative auf NULL zurück (falls Migration rückgängig gemacht wird)"""
    pass  # Kein Rollback nötig, da Daten erhalten bleiben


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0016_alter_absence_representative'),
    ]

    operations = [
        migrations.RunPython(fill_representative, reverse_fill),
    ]

