# Generated by Django 5.0.9 on 2026-01-08 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0017_fill_representative_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='representative',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='representing_absences',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Vertretung',
                help_text='Vertretung während der Abwesenheit (PFLICHT!)',
                null=False,
                blank=False
            ),
        ),
    ]
