# Generated by Django 5.0.9 on 2026-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0018_make_representative_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencetype',
            name='affects_vacation_balance',
            field=models.BooleanField(default=False, help_text='Wirkt sich auf den Urlaubssaldo aus (z.B. Urlaub, Überstunden-Abbau)'),
        ),
    ]
