# Generated by Django 5.0.9 on 2026-01-08 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0019_add_affects_vacation_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='representative',
            field=models.ForeignKey(blank=True, help_text='Vertretung während der Abwesenheit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='representing_absences', to=settings.AUTH_USER_MODEL, verbose_name='Vertretung'),
        ),
    ]
