# Generated by Django 5.0.9 on 2025-12-05 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Firmenname')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Objektname')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Ansprechpartner')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon Ansprechpartner')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='workorders.workorderclient', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Objekte',
                'ordering': ['client__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Auftragsnummer')),
                ('project_number', models.CharField(blank=True, max_length=50, verbose_name='Projektnummer')),
                ('work_type', models.CharField(max_length=200, verbose_name='Arbeitsumfang')),
                ('work_description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('start_date', models.DateField(verbose_name='Datum von')),
                ('end_date', models.DateField(verbose_name='Datum bis')),
                ('month', models.CharField(blank=True, max_length=20, verbose_name='Monat')),
                ('work_days', models.PositiveIntegerField(verbose_name='Arbeitstage')),
                ('work_schedule', models.CharField(blank=True, help_text='z.B. "5 x wö. Mo-Fr"', max_length=100, verbose_name='Arbeitszeit')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('signed', 'Unterschrieben'), ('invoiced', 'Abgerechnet'), ('cancelled', 'Storniert')], default='draft', max_length=20, verbose_name='Status')),
                ('customer_signature', models.TextField(blank=True, help_text='Base64 encoded signature image', verbose_name='Unterschrift Kunde')),
                ('customer_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unterschrieben am')),
                ('company_signature', models.TextField(blank=True, help_text='Base64 encoded signature image', verbose_name='Unterschrift Bogdol')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Bemerkung Kunde')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('work_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorders.workobject', verbose_name='Objekt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorders.workorderclient', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Arbeitsschein',
                'verbose_name_plural': 'Arbeitsscheine',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='workorders__order_n_037e72_idx'), models.Index(fields=['client', 'start_date'], name='workorders__client__e121d2_idx'), models.Index(fields=['status'], name='workorders__status_2e2089_idx')],
            },
        ),
    ]
