# Generated by Django 5.0.9 on 2025-12-05 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vorlagenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('work_type', models.CharField(max_length=200, verbose_name='Arbeitsumfang')),
                ('work_description', models.TextField(blank=True, verbose_name='Arbeitsbeschreibung')),
                ('work_days', models.IntegerField(default=1, verbose_name='Anzahl Arbeitstage')),
                ('work_schedule', models.CharField(blank=True, max_length=200, verbose_name='Arbeitszeit')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Kundennotizen')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='workorders.workorderclient', verbose_name='Kunde')),
                ('work_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='workorders.workobject', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Arbeitsschein-Vorlage',
                'verbose_name_plural': 'Arbeitsschein-Vorlagen',
                'ordering': ['client__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workorders.workordertemplate', verbose_name='Vorlage'),
        ),
    ]
