# Generated by Django 5.0.9 on 2025-12-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workordertemplate_workorder_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='scanned_document',
            field=models.ImageField(blank=True, null=True, upload_to='workorders/scans/', verbose_name='Gescannter/Fotografierter Arbeitsschein'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signature_link_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Link gesendet am'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signature_method',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('physical', 'Physisch'), ('upload', 'Foto-Upload')], max_length=20, verbose_name='Unterschriftsmethode'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signature_token',
            field=models.CharField(blank=True, help_text='Eindeutiger Token für digitale Unterschrift-Links', max_length=100, unique=True, verbose_name='Unterschrifts-Token'),
        ),
    ]
