# Generated by Django 5.0.9 on 2026-01-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_workorder_scanned_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workobject',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_objects', to='workorders.workorderclient', verbose_name='Kunde'),
        ),
    ]
