# Generated by Django 5.0.9 on 2026-01-04 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_workorder_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Erstellt'), ('updated', 'Aktualisiert'), ('submitted', 'Eingereicht'), ('billed', 'Abgerechnet'), ('status_changed', 'Status geändert'), ('assigned', 'Zugewiesen'), ('document_uploaded', 'Dokument hochgeladen'), ('cancelled', 'Storniert')], max_length=50, verbose_name='Aktion')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Alter Status')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='Neuer Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Zusätzliche Informationen (z.B. Dateiname, IP-Adresse)', verbose_name='Metadaten')),
            ],
            options={
                'verbose_name': 'Arbeitsschein-Historie',
                'verbose_name_plural': 'Arbeitsschein-Historien',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='workorders_status_submitted_idx',
        ),
        migrations.AddField(
            model_name='workorderhistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Durchgeführt von'),
        ),
        migrations.AddField(
            model_name='workorderhistory',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workorders.workorder', verbose_name='Arbeitsschein'),
        ),
        migrations.AddIndex(
            model_name='workorderhistory',
            index=models.Index(fields=['work_order', '-performed_at'], name='workorders__work_or_fef04a_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderhistory',
            index=models.Index(fields=['performed_by', '-performed_at'], name='workorders__perform_a7e8cc_idx'),
        ),
    ]
