# Generated by Django 5.0.9 on 2026-01-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_workorderhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorders.workorderclient', verbose_name='Kunde'),
        ),
    ]
