# Generated by Django 5.0.9 on 2026-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_alter_workorder_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='object_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Objektnummer'),
        ),
    ]
