# Generated by Django 5.0.9 on 2026-01-05 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_workorder_object_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='duplicate_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Duplikat-Check am'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Referenz zum Original-Arbeitsschein', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='workorders.workorder', verbose_name='Duplikat von'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Markiert wenn dieser Arbeitsschein bereits existiert', verbose_name='Ist Duplikat'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pdf_downloaded',
            field=models.BooleanField(default=False, verbose_name='PDF heruntergeladen'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pdf_downloaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF heruntergeladen am'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pdf_downloaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_workorders', to=settings.AUTH_USER_MODEL, verbose_name='PDF heruntergeladen von'),
        ),
        migrations.CreateModel(
            name='RecurringWorkOrderChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_number', models.CharField(db_index=True, help_text='Objektnummer', max_length=50, verbose_name='O-Nummer')),
                ('object_description', models.CharField(max_length=300, verbose_name='Objektbeschreibung')),
                ('project_number', models.CharField(db_index=True, help_text='Projektnummer', max_length=50, verbose_name='P-Nummer')),
                ('debitor_number', models.CharField(blank=True, help_text='Debitorennummer für Fakturierung', max_length=50, verbose_name='Debitor-Nr')),
                ('notes', models.TextField(blank=True, help_text='z.B. SR-Nummer für Sammelrechnungen (SR-123 bedeutet Arbeitsscheine können zusammengefasst werden)', verbose_name='Bemerkung')),
                ('sr_number', models.CharField(blank=True, db_index=True, help_text='Sammelrechnungs-Nummer (aus Bemerkungen extrahiert)', max_length=50, verbose_name='SR-Nummer')),
                ('current_month', models.CharField(blank=True, help_text='Format: YYYY-MM', max_length=20, verbose_name='Aktueller Monat')),
                ('checked_this_month', models.BooleanField(default=False, verbose_name='Diesen Monat abgehakt')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt abgehakt am')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='workorders.workorderclient', verbose_name='Kunde')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('last_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Zuletzt abgehakt von')),
                ('work_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='workorders.workobject', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Hakliste-Eintrag',
                'verbose_name_plural': 'Hakliste',
                'ordering': ['object_number', 'project_number'],
                'indexes': [models.Index(fields=['object_number', 'project_number'], name='workorders__object__56db7d_idx'), models.Index(fields=['sr_number'], name='workorders__sr_numb_43bed0_idx'), models.Index(fields=['current_month'], name='workorders__current_526bad_idx')],
                'unique_together': {('object_number', 'project_number')},
            },
        ),
    ]
