# Generated by Django 5.0.9 on 2026-01-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0009_workorder_duplicate_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringworkorderchecklist',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Ab wann soll dieser Eintrag in der monatlichen Hakliste erscheinen', null=True, verbose_name='Gültig von'),
        ),
        migrations.AddField(
            model_name='recurringworkorderchecklist',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Bis wann soll dieser Eintrag in der monatlichen Hakliste erscheinen', null=True, verbose_name='Gültig bis'),
        ),
    ]
