# Generated by Django 5.0.9 on 2026-01-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0010_recurringworkorderchecklist_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5-Hash aus O-Nr, P-Nr, Zeitraum, Beschreibung für Duplikat-Erkennung', max_length=64, verbose_name='Inhalts-Hash'),
        ),
    ]
