# Generated by Django 5.0.9 on 2026-01-08 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0011_workorder_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'permissions': [('cancel_workorder', 'Can cancel workorder'), ('view_all_workorders', 'Can view all workorders (toggle)')], 'verbose_name': 'Arbeitsschein', 'verbose_name_plural': 'Arbeitsscheine'},
        ),
        migrations.AddField(
            model_name='workorder',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Stornierungsgrund'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Storniert am'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_workorders', to=settings.AUTH_USER_MODEL, verbose_name='Storniert von'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Storniert'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['is_cancelled', '-created_at'], name='workorders__is_canc_4a13a1_idx'),
        ),
    ]
