# Generated by Django 5.0.9 on 2026-01-11 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0012_alter_workorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recurringworkorderchecklist',
            name='workorders__sr_numb_43bed0_idx',
        ),
        migrations.RemoveField(
            model_name='recurringworkorderchecklist',
            name='sr_number',
        ),
        migrations.AddField(
            model_name='recurringworkorderchecklist',
            name='assigned_billing_user',
            field=models.ForeignKey(blank=True, help_text='Faktur-Mitarbeiter der für die Abrechnung zuständig ist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesener Faktur-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='recurringworkorderchecklist',
            name='service_manager',
            field=models.ForeignKey(blank=True, help_text='Verantwortlicher Service Manager für diesen wiederkehrenden Auftrag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Service Manager'),
        ),
        migrations.AddField(
            model_name='recurringworkorderchecklist',
            name='sr_invoice_number',
            field=models.CharField(blank=True, db_index=True, help_text='Sammelrechnungs-Nummer für gruppierte Abrechnung (z.B. SR-2025-01)', max_length=50, verbose_name='SR-Rechnungsnummer'),
        ),
        migrations.AlterField(
            model_name='recurringworkorderchecklist',
            name='notes',
            field=models.TextField(blank=True, help_text='Freie Notizen und Hinweise', verbose_name='Bemerkung'),
        ),
        migrations.AddIndex(
            model_name='recurringworkorderchecklist',
            index=models.Index(fields=['sr_invoice_number'], name='workorders__sr_invo_284f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringworkorderchecklist',
            index=models.Index(fields=['service_manager'], name='workorders__service_b1cd57_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringworkorderchecklist',
            index=models.Index(fields=['assigned_billing_user'], name='workorders__assigne_bcd13c_idx'),
        ),
    ]
