# Generated by Django 5.0.9 on 2026-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0013_remove_recurringworkorderchecklist_workorders__sr_numb_43bed0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='leistungsmonat',
            field=models.CharField(blank=True, help_text='Monat für den die Leistung abgerechnet wird (Format: YYYY-MM)', max_length=7, null=True, verbose_name='Leistungsmonat'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='leistungsmonat_ocr_confidence',
            field=models.FloatField(blank=True, help_text='Konfidenz-Score der OCR-Erkennung für Leistungsmonat (0-100)', null=True, verbose_name='OCR-Konfidenz Leistungsmonat'),
        ),
    ]
