# Generated by Django 5.0.9 on 2026-01-12 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0014_workorder_leistungsmonat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderhistory',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='workorders.workorder', verbose_name='Arbeitsschein'),
        ),
    ]
