# Generated by Django 5.2.4 on 2025-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobil_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
