# Generated by Django 5.1.7 on 2025-09-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_customuser_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blink_company',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blink_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
