# Generated by Django 5.1.7 on 2025-09-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_customuser_blink_company_customuser_blink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='carryover_vacation',
            field=models.PositiveIntegerField(default=0, help_text='Resturlaub aus dem Vorjahr'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vacation_entitlement',
            field=models.PositiveIntegerField(default=30, help_text='Urlaubsanspruch in Tagen für das aktuelle Jahr'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vacation_year',
            field=models.PositiveIntegerField(default=2025, help_text='Jahr für das der Urlaubsanspruch gilt'),
        ),
    ]
