# Generated by Django 5.0.9 on 2025-11-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_add_vacation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, help_text='z.B. IT, HR, Vertrieb, Produktion', max_length=100, null=True, verbose_name='Abteilung'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, help_text='z.B. Verwaltung, Technik, Außendienst', max_length=100, null=True, verbose_name='Bereich/Division'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, help_text='z.B. Softwareentwickler, HR Manager, Teamleiter', max_length=100, null=True, verbose_name='Berufsbezeichnung/Titel'),
        ),
    ]
