# Generated by Django 5.0.9 on 2026-01-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_user', '0006_customuser_department_customuser_division_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Benutzer', 'verbose_name_plural': 'Benutzer'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blink_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['department', 'is_active'], name='auth_user_c_departm_f63c84_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['supervisor', 'is_active'], name='auth_user_c_supervi_7aa2d0_idx'),
        ),
    ]
