# Generated by Django 5.0.9 on 2026-01-03 09:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_alter_customuser_options_alter_customuser_blink_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='presence', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Abwesend'), ('busy', 'Beschäftigt'), ('offline', 'Offline')], default='offline', max_length=20, verbose_name='Status')),
                ('status_message', models.CharField(blank=True, help_text='z.B. "Im Meeting bis 15:00"', max_length=200, verbose_name='Statusnachricht')),
                ('is_available_for_chat', models.BooleanField(default=True, verbose_name='Chat verfügbar')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Zuletzt online')),
                ('websocket_channel_name', models.CharField(blank=True, help_text='Django Channels WebSocket Name', max_length=255, verbose_name='WebSocket Channel')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benutzerstatus',
                'verbose_name_plural': 'Benutzerstatus',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blink_company',
            field=models.IntegerField(blank=True, help_text='DEPRECATED: Nutze user.profile.blink_company', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blink_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='DEPRECATED: Nutze user.profile.blink_id', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='carryover_vacation',
            field=models.PositiveIntegerField(default=0, help_text='DEPRECATED: Nutze user.profile.carryover_vacation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, help_text='DEPRECATED: Nutze user.profile.department.name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, help_text='DEPRECATED: Nutze user.profile.department', max_length=100, null=True, verbose_name='Abteilung'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, help_text='DEPRECATED: Nutze user.profile.department.parent', max_length=100, null=True, verbose_name='Bereich/Division'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, help_text='DEPRECATED: Nutze user.profile.job_title', max_length=100, null=True, verbose_name='Berufsbezeichnung/Titel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobil_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Nutze user.profile.mobile_number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Nutze user.profile.phone_number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Nutze user.profile.direct_supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vacation_entitlement',
            field=models.PositiveIntegerField(default=30, help_text='DEPRECATED: Nutze user.profile.vacation_entitlement'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vacation_year',
            field=models.PositiveIntegerField(default=2025, help_text='DEPRECATED: Nutze user.profile.vacation_year'),
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('direct', 'Direktchat'), ('group', 'Gruppenchat')], default='direct', max_length=20, verbose_name='Typ')),
                ('name', models.CharField(blank=True, help_text='Nur für Gruppenchats', max_length=200, verbose_name='Gruppenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat/group_avatars/', verbose_name='Gruppenbild')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Nachricht')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='administered_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Administratoren')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Chat-Konversation',
                'verbose_name_plural': 'Chat-Konversationen',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'Datei'), ('image', 'Bild'), ('system', 'Systemnachricht')], default='text', max_length=20, verbose_name='Nachrichtentyp')),
                ('content', models.TextField(blank=True, verbose_name='Inhalt')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/', verbose_name='Datei')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Dateiname')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Dateigröße (Bytes)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-Type')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chat/thumbnails/%Y/%m/', verbose_name='Vorschau')),
                ('reactions', models.JSONField(blank=True, default=dict, help_text='{"👍": [user_id1, user_id2], "❤️": [user_id3]}', verbose_name='Reaktionen')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Bearbeitet')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Bearbeitet am')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Gesendet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='auth_user.chatconversation', verbose_name='Konversation')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='Gelesen von')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='auth_user.chatmessage', verbose_name='Antwort auf')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Absender')),
            ],
            options={
                'verbose_name': 'Chat-Nachricht',
                'verbose_name_plural': 'Chat-Nachrichten',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatTypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='auth_user.chatconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipp-Indikator',
                'verbose_name_plural': 'Tipp-Indikatoren',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Abteilungskürzel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Abteilungsleiter')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='auth_user.department', verbose_name='Übergeordnete Abteilung')),
            ],
            options={
                'verbose_name': 'Abteilung',
                'verbose_name_plural': 'Abteilungen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team-Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='auth_user.department', verbose_name='Abteilung')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='Team-Lead')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Mitglieder')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('display_name', models.CharField(blank=True, help_text='Optional: Abweichender Anzeigename', max_length=200, verbose_name='Anzeigename')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profilbild')),
                ('bio', models.TextField(blank=True, help_text='Kurze Beschreibung (max. 500 Zeichen)', max_length=500, verbose_name='Über mich')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'. Bis zu 15 Ziffern.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon')),
                ('mobile_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'. Bis zu 15 Ziffern.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobil')),
                ('work_extension', models.CharField(blank=True, max_length=10, verbose_name='Durchwahl')),
                ('email_backup', models.EmailField(blank=True, help_text='Alternative E-Mail-Adresse', max_length=254, verbose_name='Backup-E-Mail')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Berufsbezeichnung')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Personalnummer')),
                ('responsibilities', models.TextField(blank=True, help_text='Wofür ist diese Person zuständig? (Freitext für KI-Suche)', verbose_name='Zuständigkeiten')),
                ('expertise_areas', models.TextField(blank=True, help_text='Expertise-Bereiche (Komma-separiert oder Freitext)', verbose_name='Fachgebiete')),
                ('embedding_vector', models.JSONField(blank=True, help_text='Vector Embedding für KI-Suche (automatisch generiert)', null=True, verbose_name='Embedding Vektor')),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Embedding aktualisiert')),
                ('office_location', models.CharField(blank=True, max_length=200, verbose_name='Bürostandort')),
                ('desk_number', models.CharField(blank=True, max_length=50, verbose_name='Schreibtisch/Raum')),
                ('work_hours', models.CharField(blank=True, help_text='z.B. Mo-Fr 8:00-16:30', max_length=200, verbose_name='Arbeitszeiten')),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=50, verbose_name='Zeitzone')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Eintrittsdatum')),
                ('contract_type', models.CharField(blank=True, choices=[('full_time', 'Vollzeit'), ('part_time', 'Teilzeit'), ('contract', 'Befristet'), ('freelance', 'Freiberufler'), ('intern', 'Praktikant')], max_length=50, verbose_name='Vertragsart')),
                ('vacation_entitlement', models.PositiveIntegerField(default=30, verbose_name='Urlaubsanspruch')),
                ('carryover_vacation', models.PositiveIntegerField(default=0, verbose_name='Übertrag Vorjahr')),
                ('vacation_year', models.PositiveIntegerField(default=2026, verbose_name='Urlaubsjahr')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Notfallkontakt Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Notfallkontakt Telefon')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100, verbose_name='Verhältnis')),
                ('blink_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Blink ID')),
                ('blink_company', models.IntegerField(blank=True, null=True, verbose_name='Blink Company')),
                ('is_searchable', models.BooleanField(default=True, verbose_name='Im Verzeichnis suchbar')),
                ('show_phone_in_directory', models.BooleanField(default=True, verbose_name='Telefon anzeigen')),
                ('show_email_in_directory', models.BooleanField(default=True, verbose_name='E-Mail anzeigen')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'E-Mail'), ('phone', 'Telefon'), ('mobile', 'Mobil'), ('chat', 'Chat')], default='email', max_length=20, verbose_name='Bevorzugte Kontaktmethode')),
                ('teams_id', models.CharField(blank=True, max_length=200, verbose_name='Microsoft Teams ID')),
                ('slack_id', models.CharField(blank=True, max_length=200, verbose_name='Slack ID')),
                ('internal_notes', models.TextField(blank=True, help_text='Nur für HR/Admins sichtbar', verbose_name='Interne Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='auth_user.department', verbose_name='Abteilung')),
                ('direct_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL, verbose_name='Direkter Vorgesetzter')),
                ('functional_supervisors', models.ManyToManyField(blank=True, help_text='Für Matrix-Organisation', related_name='functional_reports', to=settings.AUTH_USER_MODEL, verbose_name='Fachliche Vorgesetzte')),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['conversation_type', '-last_message_at'], name='auth_user_c_convers_d32279_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['is_archived'], name='auth_user_c_is_arch_2d8e44_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', '-sent_at'], name='auth_user_c_convers_9d7b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-sent_at'], name='auth_user_c_sender__23a3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_deleted'], name='auth_user_c_is_dele_78d020_idx'),
        ),
        migrations.AddIndex(
            model_name='chattypingindicator',
            index=models.Index(fields=['conversation', '-started_at'], name='auth_user_c_convers_9dc111_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chattypingindicator',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent', 'is_active'], name='auth_user_d_parent__02a83f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['department', 'is_searchable'], name='auth_user_u_departm_ad8db3_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['direct_supervisor'], name='auth_user_u_direct__cc41d1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['office_location'], name='auth_user_u_office__89f141_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['employee_id'], name='auth_user_u_employe_b7c001_idx'),
        ),
    ]
