# Generated by Django 5.0.9 on 2026-01-03 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_userpresence_alter_customuser_blink_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversationHidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_for_users', to='auth_user.chatconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versteckte Konversation',
                'verbose_name_plural': 'Versteckte Konversationen',
                'unique_together': {('conversation', 'user')},
            },
        ),
    ]
