# Generated by Django 5.0.9 on 2026-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0009_chatconversationhidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether this message is end-to-end encrypted', verbose_name='Verschlüsselt'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.TextField(blank=True, help_text='RSA public key for end-to-end encryption (base64 encoded)', verbose_name='RSA Public Key'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_key_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the public key was last updated', null=True, verbose_name='Public Key Updated'),
        ),
    ]
