# Generated by Django 5.0.9 on 2026-01-03 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0010_chatmessage_is_encrypted_userprofile_public_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.AddField(
            model_name='department',
            name='org_type',
            field=models.CharField(choices=[('administration', 'Verwaltungsbereich'), ('operations', 'Betrieb'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Organisationstyp'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_members', to='auth_user.department', verbose_name='Abteilung (DEPRECATED)'),
        ),
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rollenbezeichnung')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kürzel')),
                ('hierarchy_level', models.IntegerField(default=99, help_text='1=Geschäftsführung, 2=Bereichsleitung, etc.', verbose_name='Hierarchieebene')),
                ('org_type', models.CharField(choices=[('administration', 'Verwaltungsbereich'), ('operations', 'Betrieb'), ('both', 'Beide')], default='both', max_length=20, verbose_name='Gilt für')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('color', models.CharField(default='#3880ff', max_length=7, verbose_name='Farbe (Hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisationsrolle',
                'verbose_name_plural': 'Organisationsrollen',
                'ordering': ['hierarchy_level', 'name'],
                'indexes': [models.Index(fields=['org_type', 'hierarchy_level'], name='auth_user_d_org_typ_180fef_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(blank=True, help_text='z.B. "Senior Developer", "Key Account Manager"', max_length=200, verbose_name='Positionsbezeichnung')),
                ('display_order', models.IntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('is_primary', models.BooleanField(default=True, help_text='Falls User in mehreren Departments ist', verbose_name='Primäre Zuordnung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='auth_user.department', verbose_name='Abteilung')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='auth_user.departmentmember', verbose_name='Berichtet an')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='auth_user.departmentrole', verbose_name='Rolle')),
            ],
            options={
                'verbose_name': 'Abteilungsmitglied',
                'verbose_name_plural': 'Abteilungsmitglieder',
                'ordering': ['department', 'role__hierarchy_level', 'display_order'],
                'indexes': [models.Index(fields=['user', 'is_primary', 'is_active'], name='auth_user_d_user_id_6e1a32_idx'), models.Index(fields=['department', 'is_active'], name='auth_user_d_departm_9f4fbf_idx'), models.Index(fields=['reports_to'], name='auth_user_d_reports_1890a8_idx')],
                'unique_together': {('user', 'department', 'role')},
            },
        ),
    ]
