# Generated by Django 5.0.9 on 2026-01-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0012_company_alter_department_name_department_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='User kann mehreren Gesellschaften zugeordnet sein', related_name='members', to='auth_user.company', verbose_name='Gesellschaften'),
        ),
    ]
