# Generated by Django 5.0.9 on 2026-01-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0013_userprofile_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_members', to='auth_user.departmentrole', verbose_name='Rolle (DEPRECATED)'),
        ),
    ]
