# Generated by Django 5.0.9 on 2026-01-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0014_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Keywords für KI-Suche (z.B. "Computer, Handy, Hardware, IT-Support")', verbose_name='Such-Keywords'),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Keywords für KI-Suche (z.B. "Führung, Management, Leitung")', verbose_name='Such-Keywords'),
        ),
    ]
