# Generated by Django 5.0.9 on 2026-01-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0024_userprofile_billing_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Zusätzliche Daten für absence_request, absence_decision, etc.', verbose_name='Metadaten'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'Datei'), ('image', 'Bild'), ('system', 'Systemnachricht'), ('absence_request', 'Abwesenheitsantrag'), ('absence_decision', 'Abwesenheitsentscheidung')], default='text', max_length=20, verbose_name='Nachrichtentyp'),
        ),
    ]
