# Generated by Django 5.0.9 on 2026-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0025_chatmessage_metadata_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='auth_user_c_departm_f63c84_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='auth_user_c_supervi_7aa2d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='auth_user_u_departm_ad8db3_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='blink_company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='blink_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='carryover_vacation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='division',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobil_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vacation_entitlement',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vacation_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_searchable'], name='auth_user_u_is_sear_e6d864_idx'),
        ),
    ]
