# Generated by Django 5.0.9 on 2026-01-05 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0015_absence_change_history_absence_conversation'),
        ('auth_user', '0026_cleanup_deprecated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_staff_department',
            field=models.BooleanField(default=False, help_text='Stabsstellen werden im Organigramm direkt unter GF angezeigt', verbose_name='Stabsstelle'),
        ),
        migrations.AddField(
            model_name='departmentmember',
            name='is_staff_position',
            field=models.BooleanField(default=False, help_text='Wird direkt unter GF im Organigramm angezeigt', verbose_name='Stabsstelle'),
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kürzel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('search_keywords', models.TextField(blank=True, help_text='Keywords für KI-Suche (z.B. "Rechnungsstellung, Fakturierung")', verbose_name='Such-Keywords')),
                ('display_order', models.IntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='auth_user.department', verbose_name='Abteilung')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_specialties', to='auth_user.specialty', verbose_name='Übergeordneter Fachbereich')),
            ],
            options={
                'verbose_name': 'Fachbereich',
                'verbose_name_plural': 'Fachbereiche',
                'ordering': ['department', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Grundkenntnisse'), (2, 'Fortgeschritten'), (3, 'Experte'), (4, 'Kann andere schulen')], default=3, verbose_name='Kompetenzstufe')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primär')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_assignments', to='auth_user.departmentmember', verbose_name='Abteilungsmitglied')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='auth_user.specialty', verbose_name='Fachbereich')),
            ],
            options={
                'verbose_name': 'Fachbereichszuordnung',
                'verbose_name_plural': 'Fachbereichszuordnungen',
                'ordering': ['-is_primary', 'specialty__display_order'],
            },
        ),
        migrations.CreateModel(
            name='SubstituteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='absences.absence', verbose_name='Abwesenheit')),
                ('original_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_by', to=settings.AUTH_USER_MODEL, verbose_name='Abwesender User')),
                ('specialties', models.ManyToManyField(blank=True, help_text='Leer = alle Fachbereiche des abwesenden Users', related_name='substitute_assignments', to='auth_user.specialty', verbose_name='Fachbereiche')),
                ('substitute_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituting_for', to=settings.AUTH_USER_MODEL, verbose_name='Vertretung')),
            ],
            options={
                'verbose_name': 'Vertretungszuordnung',
                'verbose_name_plural': 'Vertretungszuordnungen',
            },
        ),
        migrations.CreateModel(
            name='WorkorderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_assigned', models.BooleanField(default=True, verbose_name='Automatisch zugewiesen')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Gültig ab')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Zuständiger Faktur-Mitarbeiter')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.specialty', verbose_name='Fachbereich')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_processors', to=settings.AUTH_USER_MODEL, verbose_name='Einreichender User')),
            ],
            options={
                'verbose_name': 'Arbeitsschein-Zuordnung',
                'verbose_name_plural': 'Arbeitsschein-Zuordnungen',
            },
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['department', 'is_active'], name='auth_user_s_departm_36e274_idx'),
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['parent'], name='auth_user_s_parent__e4671d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together={('department', 'name')},
        ),
        migrations.AddIndex(
            model_name='memberspecialty',
            index=models.Index(fields=['member', 'is_active'], name='auth_user_m_member__2ed494_idx'),
        ),
        migrations.AddIndex(
            model_name='memberspecialty',
            index=models.Index(fields=['specialty', 'is_active'], name='auth_user_m_special_263c4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memberspecialty',
            unique_together={('member', 'specialty')},
        ),
        migrations.AddIndex(
            model_name='substituteassignment',
            index=models.Index(fields=['original_user', 'is_active'], name='auth_user_s_origina_d89352_idx'),
        ),
        migrations.AddIndex(
            model_name='substituteassignment',
            index=models.Index(fields=['substitute_user', 'is_active'], name='auth_user_s_substit_6f4bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='substituteassignment',
            index=models.Index(fields=['absence'], name='auth_user_s_absence_24c5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderassignment',
            index=models.Index(fields=['submitter', 'is_active'], name='auth_user_w_submitt_1b0340_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderassignment',
            index=models.Index(fields=['processor', 'is_active'], name='auth_user_w_process_7fdff7_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderassignment',
            index=models.Index(fields=['specialty'], name='auth_user_w_special_f93d03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorderassignment',
            unique_together={('submitter', 'processor', 'specialty')},
        ),
    ]
