# Generated by Django 5.0.9 on 2026-01-06 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0027_add_specialty_and_assignment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500, verbose_name='Such-Query')),
                ('result_count', models.IntegerField(default=0, verbose_name='Anzahl Ergebnisse')),
                ('avg_score', models.FloatField(blank=True, null=True, verbose_name='Durchschnittlicher Score')),
                ('has_click', models.BooleanField(default=False, verbose_name='Ergebnis angeklickt')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zeitpunkt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Such-Anfrage',
                'verbose_name_plural': 'Such-Anfragen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('relevance_score', models.FloatField(verbose_name='Relevanz-Score')),
                ('time_on_page', models.IntegerField(blank=True, null=True, verbose_name='Zeit auf Seite (Sekunden)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('clicked_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_clicks', to='auth_user.userprofile', verbose_name='Angeklicktes Profil')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='auth_user.searchquery', verbose_name='Such-Anfrage')),
            ],
            options={
                'verbose_name': 'Such-Klick',
                'verbose_name_plural': 'Such-Klicks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True, verbose_name='Begriff')),
                ('synonyms', models.TextField(help_text='Komma-separierte Liste von Synonymen', verbose_name='Synonyme')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Automatisch generiert')),
                ('weight', models.FloatField(default=0.8, help_text='0.0 - 1.0', verbose_name='Gewichtung')),
                ('scope', models.CharField(blank=True, help_text='z.B. "IT", "Verwaltung", leer = global', max_length=50, verbose_name='Gültigkeitsbereich')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Such-Synonym',
                'verbose_name_plural': 'Such-Synonyme',
                'ordering': ['term'],
                'indexes': [models.Index(fields=['term', 'is_active'], name='auth_user_s_term_b165ed_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['query_text', '-created_at'], name='auth_user_s_query_t_0462a1_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user', '-created_at'], name='auth_user_s_user_id_57d077_idx'),
        ),
        migrations.AddIndex(
            model_name='searchclick',
            index=models.Index(fields=['search_query', 'position'], name='auth_user_s_search__f54f91_idx'),
        ),
        migrations.AddIndex(
            model_name='searchclick',
            index=models.Index(fields=['clicked_profile', '-created_at'], name='auth_user_s_clicked_5ed78f_idx'),
        ),
    ]
