# Generated by Django 5.0.9 on 2026-01-06 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0028_searchquery_searchclick_searchsynonym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfileMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_term', models.CharField(help_text='z.B. "drucker problem", "rechnung", "urlaub"', max_length=255, verbose_name='Suchbegriff')),
                ('boost_score', models.FloatField(default=0.3, help_text='0.0 - 1.0, wird zum Score addiert', verbose_name='Boost-Wert')),
                ('priority', models.IntegerField(default=1, help_text='Höhere Zahl = höhere Priorität', verbose_name='Priorität')),
                ('notes', models.TextField(blank=True, help_text='Warum diese Zuordnung?', verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_mappings', to='auth_user.userprofile', verbose_name='Zugeordnetes Profil')),
            ],
            options={
                'verbose_name': 'Such-Zuordnung',
                'verbose_name_plural': 'Such-Zuordnungen',
                'ordering': ['-priority', 'query_term'],
                'indexes': [models.Index(fields=['query_term', 'is_active'], name='auth_user_s_query_t_159213_idx'), models.Index(fields=['-priority'], name='auth_user_s_priorit_9772f9_idx')],
                'unique_together': {('query_term', 'profile')},
            },
        ),
    ]
