# Generated by Django 5.0.9 on 2026-01-08 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0029_searchprofilemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Gültig ab')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Optional: Für welches Department gilt die Zuweisung', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.department', verbose_name='Abteilung')),
                ('employee', models.ForeignKey(help_text='Mitarbeiter der betreut wird', on_delete=django.db.models.deletion.CASCADE, related_name='hr_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
                ('hr_processor', models.ForeignKey(help_text='HR-Mitarbeiter der zuständig ist', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_hr_employees', to=settings.AUTH_USER_MODEL, verbose_name='HR-Mitarbeiter')),
            ],
            options={
                'verbose_name': 'HR-Zuweisung',
                'verbose_name_plural': 'HR-Zuweisungen',
                'db_table': 'auth_user_hr_assignment',
                'indexes': [models.Index(fields=['employee', 'is_active'], name='auth_user_h_employe_d7c900_idx'), models.Index(fields=['hr_processor', 'is_active'], name='auth_user_h_hr_proc_edf2d0_idx'), models.Index(fields=['department'], name='auth_user_h_departm_661ff6_idx')],
                'unique_together': {('employee', 'hr_processor')},
            },
        ),
    ]
