# Generated by Django 5.0.9 on 2026-01-09 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0030_hrassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakturaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Gültig ab')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Optional: Für welches Department gilt die Zuweisung', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.department', verbose_name='Abteilung')),
                ('employee', models.ForeignKey(help_text='Mitarbeiter der betreut wird', on_delete=django.db.models.deletion.CASCADE, related_name='faktura_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
                ('faktura_processor', models.ForeignKey(help_text='Faktura-Mitarbeiter der zuständig ist', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_faktura_employees', to=settings.AUTH_USER_MODEL, verbose_name='Faktura-Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Faktura-Zuweisung',
                'verbose_name_plural': 'Faktura-Zuweisungen',
                'db_table': 'auth_user_faktura_assignment',
                'indexes': [models.Index(fields=['employee', 'is_active'], name='auth_user_f_employe_34ebd6_idx'), models.Index(fields=['faktura_processor', 'is_active'], name='auth_user_f_faktura_165078_idx'), models.Index(fields=['department'], name='auth_user_f_departm_81a160_idx')],
                'unique_together': {('employee', 'faktura_processor')},
            },
        ),
    ]
