# Generated by Django 5.0.9 on 2026-01-09 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0031_fakturaassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Eindeutiger Code, z.B. can_view_workorders', max_length=100, unique=True, verbose_name='Permission Code')),
                ('name', models.CharField(help_text='Anzeigename für Frontend', max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Was erlaubt diese Permission?', verbose_name='Beschreibung')),
                ('category', models.CharField(choices=[('APP', 'Apps & Features'), ('ADMIN', 'Administration'), ('WORKORDER', 'Arbeitsscheine'), ('ABSENCE', 'Abwesenheiten'), ('USER', 'Benutzerverwaltung'), ('DEPARTMENT', 'Abteilungsverwaltung'), ('ANALYTICS', 'Auswertungen'), ('OTHER', 'Sonstige')], default='OTHER', max_length=50, verbose_name='Kategorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('display_order', models.IntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Code',
                'verbose_name_plural': 'Permission Codes',
                'ordering': ['category', 'display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PermissionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('DEPARTMENT', 'Abteilung'), ('ROLE', 'Rolle'), ('SPECIALTY', 'Fachbereich'), ('GROUP', 'Django Group')], max_length=20, verbose_name='Entity-Typ')),
                ('entity_id', models.IntegerField(help_text='ID der Department/Role/Specialty/Group', verbose_name='Entity ID')),
                ('object_type', models.CharField(blank=True, help_text='Optional: z.B. "workorder", "absence" für objektspezifische Rechte', max_length=50, verbose_name='Objekt-Typ')),
                ('object_id', models.IntegerField(blank=True, help_text='Optional: ID des spezifischen Objekts', null=True, verbose_name='Objekt-ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permission_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='auth_user.permissioncode', verbose_name='Permission')),
            ],
            options={
                'verbose_name': 'Permission Mapping',
                'verbose_name_plural': 'Permission Mappings',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='auth_user_p_entity__597fc7_idx'), models.Index(fields=['permission', 'is_active'], name='auth_user_p_permiss_4ab872_idx')],
                'unique_together': {('entity_type', 'entity_id', 'permission', 'object_type', 'object_id')},
            },
        ),
    ]
