# Generated by Django 5.0.9 on 2026-01-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0032_add_permission_mapping_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentrole',
            name='can_receive_faktura_assignments',
            field=models.BooleanField(default=False, help_text='Mitarbeiter mit dieser Rolle können von Faktura-Mitarbeitern zugewiesen werden (z.B. Service Manager)', verbose_name='Kann Faktura-Zuweisungen erhalten'),
        ),
    ]
