# Generated by Django 5.0.9 on 2026-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0033_add_faktura_assignment_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissioncode',
            name='default_scope',
            field=models.CharField(choices=[('NONE', 'Keine Einschränkung'), ('OWN', 'Nur eigene'), ('DEPARTMENT', 'Eigene Abteilung'), ('ALL', 'Alle')], default='NONE', help_text='Standard-Geltungsbereich dieser Permission (kann pro Mapping überschrieben werden)', max_length=20, verbose_name='Standard-Scope'),
        ),
        migrations.AddField(
            model_name='permissioncode',
            name='supports_scope',
            field=models.BooleanField(default=False, help_text='Kann diese Permission unterschiedliche Scopes haben? (z.B. eigene vs. alle Arbeitsscheine)', verbose_name='Unterstützt Scope'),
        ),
        migrations.AddField(
            model_name='permissionmapping',
            name='scope',
            field=models.CharField(blank=True, choices=[('NONE', 'Keine Einschränkung'), ('OWN', 'Nur eigene'), ('DEPARTMENT', 'Eigene Abteilung'), ('ALL', 'Alle')], help_text='Überschreibt den Standard-Scope. Leer = nutze default_scope der Permission', max_length=20, null=True, verbose_name='Geltungsbereich'),
        ),
    ]
