"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from decouple import config, Csv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY', default='django-insecure-8st_!p7k6!1i-daux!v-)kjr-5dez8x$)99(i2_ofm+(7^4@4s')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS = ['*'] 
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0', cast=Csv())

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:4200,http://localhost:8100,http://127.0.0.1:8100',
    cast=Csv()
)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # Für Production sollte das False sein

# Cookie-Einstellungen für Development (weniger restriktiv)
SESSION_COOKIE_SAMESITE = 'Lax'  # 'Lax' funktioniert besser für localhost als None
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_DOMAIN = None  # Für localhost
CSRF_COOKIE_DOMAIN = None     # Für localhost
# Application definition

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://10.1.201.146:8000",
    "http://10.1.201.67:8000",
    "http://10.1.201.134:8000",
    "http://10.1.180.22:8000",
    "http://192.168.178.113:8000",
]

INSTALLED_APPS = [
    'daphne',  # Django Channels ASGI server
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # Django Channels
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'guardian',
    'rules',
    'auth_user',
    'sofortmeldung',
    'absences',
    'blink_integration',
    'contacts',
    'core',
    'workorders',
    # Celery & Redis
    'django_celery_beat',
    'django_celery_results', 
    'django_redis',
]

# Cookie-Einstellungen für Development
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='bogdol_go_new'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='!Joni#3487'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'auth_user.CustomUser'

# Guardian Settings - Verhindert automatische AnonymousUser-Erstellung
ANONYMOUS_USER_NAME = None  # Deaktiviert AnonymousUser komplett

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    # False für Development - sonst Race Condition bei gleichzeitigen Requests
    # Wenn mehrere Requests gleichzeitig refreshen, nutzen alle den gleichen alten Token
    # Nur der erste bekommt einen neuen - die anderen schlagen fehl weil Token geblacklistet
    'BLACKLIST_AFTER_ROTATION': False,
}

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'p.offermanns@bogdol.gmbh'
# EMAIL_HOST_PASSWORD = 'Sofomail'
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.strato.de')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='patrick@offermanns.dev')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='!Joni#3487+?Nessi#8752')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# =============================================================================
# BLINK API CONFIGURATION (SECURE)
# =============================================================================
BLINK_API_BASE = config('BLINK_API_BASE', default='https://bogdol-api.blink.online')
BLINK_USERNAME = config('BLINK_USERNAME', default='p.offermanns@bogdol-dienstleistungen.de')
BLINK_PASSWORD = config('BLINK_PASSWORD', default='Joni#3487')

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'blink_integration': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
# Celery Settings
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Celery Beat
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Task Routes für Queue-Management
CELERY_TASK_ROUTES = {
    'blink_integration.tasks.*': {'queue': 'blink'},
    'absences.tasks.*': {'queue': 'absences'},
    'sofortmeldung.tasks.*': {'queue': 'sofortmeldung'},
    'core.tasks.*': {'queue': 'default'},
    'auth_user.tasks.*': {'queue': 'default'},
}

# Task Settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 Minuten
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 Minuten
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# =============================================================================
# REDIS CONFIGURATION  
# =============================================================================
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 20,
                'retry_on_timeout': True,
            },
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        },
        'KEY_PREFIX': 'bogdol_go',
        'TIMEOUT': 300,  # 5 Minuten default
    }
}

# Session Storage auf Redis
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 24 Stunden

# =============================================================================
# DOCKER/PRODUCTION SETTINGS
# =============================================================================
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES['default'] = dj_database_url.parse(os.environ.get('DATABASE_URL'))

# Static Files für Docker
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# HR Email für Benachrichtigungen
HR_EMAIL = config('HR_EMAIL', default='hr@bogdol.gmbh')

# =============================================================================
# SOFORTMELDER API CONFIGURATION
# =============================================================================
SORFORTMELDER_API_URL = config('SOFORTMELDER_API_URL', default='https://api.sofortmelder.de')
SORFORTMELDER_REFRESH_TOKEN = config('SOFORTMELDER_REFRESH_TOKEN', default='ciDhXvcxShO8yAuugsHa1dQwFTIPmcXsDbQR80FrpwIW8osACVBUCsneGJnaFG2sJz83oGxZrIm49KRiAlHcwPsI6c1EVFm76sq6jKsiLjRfsEFJYrTih7Jb6fttlA46')
SORFORTMELDER_COMPANY_NUMBER = config('SOFORTMELDER_COMPANY_NUMBER', default='15308598')
SORFORTMELDER_ACCESS_TOKEN = config('SOFORTMELDER_ACCESS_TOKEN', default='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiY2xpZW50X2NvbXBhbnlfZW1haWwiOiJwLm9mZmVybWFubnNAYm9nZG9sLmdtYmgiLCJpYXQiOjE3NTczMjc3ODQsImV4cCI6MTc4ODg2Mzc4NH0.2iJeLfMJqrMc8hwcOili24pkQnWj-IZVkH4TJmeiT8c')

# =============================================================================
# SECURITY SETTINGS FOR PRODUCTION
# =============================================================================
if not DEBUG:
    # Production Security Settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_SECONDS = 31536000
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'

# =============================================================================
# CHANNELS CONFIGURATION
# =============================================================================
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('redis', 6379)],
            'capacity': 1500,
            'expiry': 10,
        },
    },
}
EMBEDDING_CONFIG = {
    # Wähle Provider: 'sentence_transformers', 'ollama', oder 'openai'
    'provider': config('EMBEDDING_PROVIDER', default='sentence_transformers'),
    
    # Für Sentence Transformers
    'model': config('EMBEDDING_MODEL', default='all-MiniLM-L6-v2'),
    
    # Für Ollama (lokal, kostenfrei)
    'base_url': config('OLLAMA_BASE_URL', default='http://localhost:11434'),
    
    # Für OpenAI (online, kostenpflichtig)
    # OPENAI_API_KEY muss in Umgebung gesetzt sein
    'openai_model': config('OPENAI_EMBEDDING_MODEL', default='text-embedding-3-small'),
}

# LOGGING für Embedding-Service
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'auth_user.embedding_service': {
            'handlers': ['console'],
            'level': config('LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'auth_user.embedding_tasks': {
            'handlers': ['console'],
            'level': config('LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}